### ISSUE TITLE
RFP proposal: alternative javascript console for polkadot js API 

### ISSUE THREAD

**Issue by muddlebee** [w3f/Grants-Program#1235]
![image](https://user-images.githubusercontent.com/8139783/197954316-1449075f-b8be-4a30-a759-873c15f8a14f.png)

**Link** - [https://polkadot.js.org/apps/#/js](https://polkadot.js.org/apps/#/js)

### Current state
We have a Javascript console at the Developer tab which is really useful for running polkadot js API scripts [https://polkadot.js.org/docs/api/cookbook/blocks](https://polkadot.js.org/docs/api/cookbook/blocks)

alternative polkadot js API playground
1. [https://github.com/subdirectory/subshell](https://github.com/subdirectory/subshell)

**Current limitations**
cannot save code properly, not much keyboard shortcuts, cannot customize configurations.

### Proposed RFP
A new javascript playground with vs-code like configurations like save the code, workspace, keyboard shortcuts etc etc..
[https://polkadot.js.org/apps/#/js](https://polkadot.js.org/apps/#/js)

some examples -> https://playground.substrate.dev/
here we have to manually build and run our rust/js files, 
![image](https://user-images.githubusercontent.com/8139783/198254152-abdd0f2e-62d4-4f0f-aad1-bcfdd6d48a74.png)

where as in case of existing javascipt consoles I shared in beginning of this post, the polkadot JS API libraries comes preloaded so basically we can paste any script and make it run..

**Comment by 0xCaso** [comment]
Hi @muddlebee. Apologies if we reply now, but we don't look at the Issues at all. May I ask you to re-write the RFP following the [suggestion template](https://github.com/w3f/Grants-Program/blob/master/docs/RFPs/suggestion-template.md), and then open a Pull Request:
- adding the `your-rfp-name.md` document inside the [`Grants-Program/docs/RFPs/Open`](https://github.com/w3f/Grants-Program/tree/master/docs/RFPs/Open) folder;
- adding a row in the table [here](https://github.com/w3f/Grants-Program/blob/master/docs/rfps.md#-list-of-rfps).

Once you do it, the Committee will review and discuss it. Thanks a lot and sorry again.

**Comment by muddlebee** [comment]
thanks @0xCaso 
I will send a PR

**Comment by 0xCaso** [comment]
No worries! [Here](https://github.com/w3f/Grants-Program/blob/master/.github/PULL_REQUEST_TEMPLATE/rfp_pr_template.md) you can find the template for the pull request.
