### ISSUE TITLE
[Idea Suggestion] Common Digital Identification Project

### ISSUE THREAD

**Issue by fixuni** [w3f/Grants-Program#1320]
Hello, I'm Gwon OhGyoung of South Korea, who is working on a project related to Self-Sovereign Identity.

I am contacting you because I heard about the WEB3 Foundation's activities and thought there might be a possibility of collaboration.

Currently, I have been planning a project called Common Digital Identifier alone. Attached is the related file. It is about Electronic ID Card system using Absolute Identifier & Switchable Identifier.

I aim to contribute to public ecosystem by forming an alliance of private activists, IT, law, and medical experts for the commercialization of the solution. Based on domestic patent rights, individual overseas countries (the United States, EU, China, Japan) gradually increasing their patent registrations.

Currently, I am aware of the limitations due to the rigid political situation, and I thought global NGO's  possibility digital introduction precedent is greater. After all, I am looking for a organization to donate patents to digital solution-based non-profit project and use my patents well. And I recognized there should be a Technical standard organization to support this.

Also, I have another idea that mixes absolute and relative evaluation from a more ultimate and long-term perspective. If you want to know the details, please check the open source document on our homepage.

I hope it can be a good relationship. Thank you! 

[PichDeck](https://drive.google.com/file/d/17yI10WTnsOuFySn69J29oijLyKx2YiRw/view?usp=sharing) 

[homepage](http://www.ahnist.com)

**Comment by semuelle** [comment]
Hi @fixuni. I sent you an email responding to your grant application earlier today. Since you applied for a private grant, I'll close this issue and we'll continue the conversation by email.

**Comment by fixuni** [comment]
> Hi @fixuni. I sent you an email responding to your grant application earlier today. Since you applied for a private grant, I'll close this issue and we'll continue the conversation by email.

I see. Thank you for your interest even though this is a difficult project to cooperate with. If you need anything else for cooperation, please feel free to tell me. I'll respond.
