### ISSUE TITLE
Start Up Idea

### ISSUE THREAD

**Issue by gauharyes** [w3f/Grants-Program#1609]
Hello, my name is Gaukhar, I am one of the co-founders of Meta Drip, a web3.0 start up. Myself and my co-founder Sunny would like to apply for the Grants, however we lack technical coding experience. 
Our platform is based on blockchain in the NFT space. 

Please advice if we are qualified for this program. 
Best email to reach me at is gaukhar.yess@gmail.com

Thank you, 
Gaukhar

**Comment by semuelle** [comment]
Responded by email.
