### ISSUE TITLE
Change of payment address

### ISSUE THREAD

**Issue by salaheldinsoliman** [w3f/Grants-Program#1688]
Hello, It seems that I have uploaded a wrong public address for my payment for https://github.com/w3f/Grants-Program/pull/1334/files .
I have completed the first milestone and filled the invoice. please contact me asap regarding this issue. Thanks

**Comment by salaheldinsoliman** [comment]
@qstnus @Noc2 @keeganquigley @alxs

**Comment by Noc2** [comment]
Thanks for creating the issue. Please contact us via email: grants@web3.foundation and put invoices@web3.foundation in CC. In the meantime, I told the invoice team to put the invoice on hold in case we haven't paid it yet.

**Comment by Noc2** [comment]
Fyi: I have just received confirmation that we still need to pay it.

**Comment by salaheldinsoliman** [comment]
Thanks for the quick reply!
I will contact the provided email now.
