### ISSUE TITLE
Grants Eligibility

### ISSUE THREAD

**Issue by 0xtimosarkar** [w3f/Grants-Program#1699]
Hi All

Just wanted to ask if only projects building on polkadot stack are eligible for a grant. Do you also support Ethereum Projects?

Thanks and best regards

Timo

**Comment by semuelle** [comment]
Hi Timo, sorry I didn't reply sooner. The W3F Grants Program is looking for projects that benefit the Substrate, Polkadot and Kusama ecosystems. Several teams and parachains here are EVM-compatible, so there is a bit of an overlap, but if you are planning to operate on Ethereum exclusively, wo won't support it.

Let me know if you have any further questions!
