### ISSUE TITLE
Broken image links on the README

### ISSUE THREAD

**Issue by laboon** [w3f/Grants-Program#1700]
The images under ["Additional Information"](https://github.com/w3f/Grants-Program#additional-information) are broken.

See: 
![Screenshot 2023-04-27 at 09 35 05](https://user-images.githubusercontent.com/1417717/234792483-41c48851-741c-4576-886b-261a4054c5df.png)

**Comment by Noc2** [comment]
I'm closing the issue, since it's fixed see: https://github.com/w3f/Grants-Program#additional-information
