### ISSUE TITLE
Three RFPs for "easy" crypto implementation

### ISSUE THREAD

**Issue by burdges** [w3f/Grants-Program#505]
I think https://github.com/arkworks-rs/algebra/issues/730 should be straightforward if you know both the substrate wasm boundary and elliptic curves, but probably nobody knows both. 

---

I think https://github.com/kobigurk/aggregatable-dkg/issues/1 should be easy, but it'd fall more to the original authors, but if someone were interested..

---

I implemented deliniearized witness multi-signatures in https://github.com/w3f/schnorrkel/blob/master/src/musig.rs in the commit https://github.com/w3f/schnorrkel/commit/fa6c35f832a4ae6f45e9c8e6858d90d1e2789fc7#diff-6ed16ffe933791b81e8340007a820ced7a47171ced9ce5378262d152951ec20d but at that time I'd no security proof so I kept the code encouraging the three round trip version.

We now have a security proof in https://eprint.iacr.org/2020/1245 and Isis Lovecruft did a nice implementation of the two round trip version in https://github.com/isislovecruft/frost-dalek/ so we should really rip out my code and replace it with theirs.  I could do this but so could many other people.

A second implementation seems to be progressing in https://github.com/ZcashFoundation/redjubjub but its further from ristretto

---

I'd suspect generous gitcoin level bounties suffice for the all three of these.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/implement-crypto-primitives-and-confidential-transfer-pallet/2569/1

**Comment by Noc2** [comment]
I'm closing this issue since it has been open for a very long time.
