### ISSUE TITLE
api.rpc.payment.queryInfo is not a function

### ISSUE THREAD

**Issue by shixm1102** [w3f/Grants-Program#617]
How do I estimate the transaction fees?

endpoint: wss://gamma.subgame.org/

I'm trying to get this value with the following code:
const info = await api.tx.balances
.transfer(recipient, amount)
.paymentInfo(sender);

Execution issue:
TypeError: api.rpc.payment.queryInfo is not a function

**Comment by mmagician** [comment]
This is probably not the best place to ask this question. Try directly with the subgame team: https://github.com/SubGame-Network
