### ISSUE TITLE
Status quo of RFP: Identity Directory

### ISSUE THREAD

**Issue by hanwencheng** [w3f/Grants-Program#648]
We are very interested in the RFP of [identity directory](https://github.com/w3f/Grants-Program/blob/master/rfps/identity-directory.md), I see there is an expected team to work on that, what to make sure if the RFP is still open? if so, will @swader or RMRK team collaborate on the RFP?

**Comment by Swader** [comment]
Thank for the ping, yes, we won't be doing anything about this in the near future but I'm open to collaborating with any party wishing to take this all the way

**Comment by hanwencheng** [comment]
Thanks for both of your explanations, I think https://identityhub.xyz/ is doing a good job, close the issue.

**Comment by hanwencheng** [comment]
is the https://identityhub.xyz/ still WIP? I can't access to it.

**Comment by alxs** [comment]
@hanwencheng as far as we can tell the team abandoned the project. It's publicly available under https://github.com/Shard-Labs/identity-hub

**Comment by hanwencheng** [comment]
Thank you, we will see what we can do about it.

**Comment by alxs** [comment]
Also note that another team just applied for this RFP, see https://github.com/w3f/Grants-Program/pull/877
