### ISSUE TITLE
 links to Darwinia Grants Program are broken from the w3f Grants Program Github.

### ISSUE THREAD

**Issue by 1022ranji** [w3f/Grants-Program#720]
hi team! links to Darwinia Grants Program are broken from the w3f Grants Program Github. 
https://github.com/w3f/Grants-Program#web3-foundation-grants-program
![image](https://user-images.githubusercontent.com/80877629/144342218-1c06ea18-2bac-45a8-96c8-e87cf727d36d.png)
Please use this link to replace:
https://docs.darwinia.network/developers/dev-bounty

**Comment by semuelle** [comment]
Thanks for raising this, @1022ranji. Fix was already submitted and should be merged very soon.

**Comment by 1022ranji** [comment]
Thanks!
