### ISSUE TITLE
Plant 2 million Trees with our NFT'S!

### ISSUE THREAD

**Issue by UnearthedDesigns** [w3f/Grants-Program#779]
We have a new project focused on reforestation efforts.
Unearthed Designs plans on having a 6 piece collection of NFT'S that will fund our reforestation efforts. Purchase 2,500, 4,000, 10,000, 14,000, 23,000, or 52,000 Trees per NFT. This will greatly reduce our carbon footprint, and bridge the gap between Blockchain and forest restoration. Once we reach our 2 million Tree goal the remainder of the first collection will be burned locking in the amount of each one available. A second collection will be minted to support our next goal of 10 Million trees with our NFTS. Over time we would like to expand into even more humanitarian efforts driven by blockchain utilities. With the help of our partnerships we plan on planting trees in countries all over the world and becoming a major contributor in worldwide reforestation and ecological restoration efforts. Here is a link to our website, Https://uneartheddesignsllc.com We look forward to gaining an abundant amount of partners and contributors and would love to have you along for the ride. 
Thank you - Andy

**Comment by Noc2** [comment]
Hi Andy, Web3 Foundation doesn’t partner with any project and since this issue is unrelated to our grants program or our ecosystem, I’m going to close it. Please don’t use this repository, for advertising purposes.
