### ISSUE TITLE
Shootingstars, spacechainz, 

### ISSUE THREAD

**Issue by 9ightmare** [w3f/Grants-Program#787]
I have a project idea, I hope I find developers and grant for it, plus I need a guide on how I can start about it here

**Comment by 9ightmare** [comment]
![Screenshot_20220117_020740.jpg](https://user-images.githubusercontent.com/74509480/149886450-a67afccc-368d-4b1c-a0bc-77ab8410d557.jpg)

**Comment by 9ightmare** [comment]
![Screenshot_20220117_032537.jpg](https://user-images.githubusercontent.com/74509480/149886542-93eb8ba8-8cd7-409e-bc91-2fca91f870c1.jpg)

**Comment by 9ightmare** [comment]
![Screenshot_20220117_031646.jpg](https://user-images.githubusercontent.com/74509480/149886636-c4f6812c-a9f4-44fb-ac09-978f948d9628.jpg)

**Comment by 9ightmare** [comment]
![Screenshot_20220117_012921.jpg](https://user-images.githubusercontent.com/74509480/149886684-974648c9-8642-41d5-8e35-ceee98673f91.jpg)

**Comment by 9ightmare** [comment]
![Screenshot_20220117_015803.jpg](https://user-images.githubusercontent.com/74509480/149886733-2915f416-7acd-4d62-ba65-50a54808bfee.jpg)

**Comment by Noc2** [comment]
Thanks for the interest in the grant program. I recommend to follow the process here: https://github.com/w3f/Grants-Program#pencil-process and to create a PR based on the application template. In general, you should provide as many technical details about your project as possible. We don’t care so much about token economics or tokennames and marketing material in general. Let me know if you have any other questions. I’m closing the issue for now.
