### ISSUE TITLE
Low/No-code Middleware for Web3 - request for feedback

### ISSUE THREAD

**Issue by edbong123** [w3f/Grants-Program#875]
hey guys, before going through the effort of applying for a grant could we get some feedback on this whitepaper?
https://drive.google.com/file/d/1SI5bK0F8FrDN5C23XTGOpUG7Pdfmzp-A/view?usp=sharing
Please feel free to reach out to me directly for questions.
https://telegram.me/edbong

:)

**Comment by semuelle** [comment]
Makes sense. 

I''ll close this issue. Let me know if you have any further questions.

**Comment by edbong123** [comment]
@semuelle as follow up to this we made a grant submission va the website. We would love to get a heads up. Who do we check in with?

**Comment by semuelle** [comment]
Which website?

**Comment by edbong123** [comment]
Here https://web3.foundation/grants/
Should I repost here instead?

**Comment by semuelle** [comment]
Where did you go from there? Because the `Apply` button links to this repo, and I don't see a PR from you. Did you submit a PR, fill out a form, or something else?

**Comment by edbong123** [comment]
We filled out a form

**Comment by edbong123** [comment]
Strange.

**Comment by semuelle** [comment]
I checked and couldn't find a submission by the name in our data. Sorry about that. Did you receive an email with a link to your submission? That's a sure sign that it was properly submitted.

**Comment by edbong123** [comment]
I did not see anything. Did double check.
Resubmit here or use the form?
Whats better?

**Comment by edbong123** [comment]
Will do that!

**Comment by edbong123** [comment]
Sebastian, could you add me to TG?  have a few questions. 
We are in a super exciting moment and might do more things with you guys than we initially had in mind.
https://telegram.me/edbong

**Comment by edbong123** [comment]
Sebastian, could you add me to TG?
I have a few questions.
We are in a super exciting moment and might do more things with you guys
than we initially had in mind.

**Comment by edbong123** [comment]
Over the website.
Should I repost here?
